### ISSUE TITLE
Upgrade ServiceControl to RavenDb 3

### ISSUE THREAD

**Issue by boblangley** [Particular/ServiceControl#728]
Taskforce:

## Task Force Formation

@boblangley @johnsimons @mikeminutillo 

## Justifications for Promotion

1. This is a quick win for stability. We have seen situations where ServiceControl loses stability under very high load. Initial testing shows that the upgrade to Raven 3 greatly improves this. 
  - Under Raven 2.5, when the background purge task happens to delete old messages, ingestion rates drop dramatically. In some systems, this drop can lead to a situation where SC is unable to ever catch up even after the purge has completed. Under Raven 3, the deletes take longer to complete but we see very little impact on ingestion rates. Arguably, it is more important to keep ingesting new messages with lower latency then to delete old messages.
  - We see less garbage collector pressure.
  - We see overall lower resource utilization.
2. It lays the groundwork for componentization effort.
  - Raven 3 uses the same interfaces for embedded DBs as external DBs making it easier to externalize the data store
  - Raven 3 allows us to create additional databases in embedded mode so we are not confined to the system database. This would allow us to store data in separate databases with separate indexes as we undergo the componentization effort. This in turn will lead to easier physical separation if and when we decide to go down that route.
3. The new version of the Studio allows much better diagnostics
4. The new version of the Studio allows users to do database compaction interactively
5. Uses a single OWIN pipeline for both the `/api` and the `/storage`
6. `/storage` is now using Windows Authentication, which allows admins to administer it via the Studio
7. The new version of the Raven Studio does not require Silverlight. Silverlight on servers is a not acceptable for some customers.  

## Plan Of Attack

- [ ] Task Force PR Code Review
- [ ] Complete [PR](https://github.com/Particular/ServiceControl/pull/720)
    - [ ] URL ACLs
    - [ ] Lucene Schema Update
    - [ ] NSB.Raven Package (if possible, but not required)
- [ ] Internal demo recording published (demo of upgrade / configuration options added)
- [ ] Testing:
       - [ ] Upgrade experience (non TF user)
       - [ ] Fresh installation;
       - [ ] Performance - re-use recent performance testing 
       - [ ] Memory Usage
       - [ ] Shutdown timings
       - [ ] Standard Use Cases
          - [ ] Archive
          - [ ] Retry
          - [ ] Purging
          - [ ] Plugins
             - [ ] SagaAudit
             - [ ] Custom Checks
             - [ ] Heartbeats
             - [ ] DebugSession
- [ ] Update Doco:
    - [ ] Installing SC
    - [ ] Settings
- [ ] Release to a subset of customers (kind of a RC release)
- [ ] Announcement
    - [ ] Direct communication to SC users

**Comment by distantcam** [comment]
Ok this is next in line and needs taskforce members. Ideally there should be at least one @Particular/servicecontrol-maintainers 

So who want's to work on this?

**Comment by johnsimons** [comment]
We now have a complete task force and I am leading it

**Comment by distantcam** [comment]
Ok. This issue needs a size estimate, and the plan of attack needs to be fleshed out, specifically items 2 and 3.

**Comment by johnsimons** [comment]
Done

**Comment by distantcam** [comment]
If Greg is part of this taskforce then it cannot go into progress until he returns from leave.

**Comment by gbiellem** [comment]
@distantcam. Sees odd. We don't take other TFs offline when one member is
on leave. Why can't the existing members make a start with out me? I'll be
back on the 30th

**Comment by johnsimons** [comment]
We are ready to start now, Greg will join us when he comes back.
BTW @distantcam, as u can see we have set the size to be a Medium and as u know by definition of that size it actually only requires 1-2 people, hence we are meeting the quota necessary.

**Comment by johnsimons** [comment]
@mikeminutillo even though you are not part of this TF, as a maintainer I need you to code review the PR if that is ok ?

**Comment by distantcam** [comment]
This taskforce needs to be discussed by the @Particular/platform-dev-squad before it can go into progress. I'm sorry, but please stop putting it into progress until that discussion happens.

**Comment by johnsimons** [comment]
Ok, you guys go ahead and discuss it.

**Comment by andreasohlund** [comment]
Call scheduled for monday morning 8AM GMT+1

**Comment by gbiellem** [comment]
I won't be attending the meeting - please record it and I'll catch up on the 30th

**Comment by mauroservienti** [comment]
I'm back, my availability is still a bit limited till the end of NDC, however if you need me ping me :smile:

**Comment by gbiellem** [comment]
@andreasohlund  I watched the recording for the meeting about this and the last thing that happened was that it was moved to in progress.  Now it's back in the backlog.  Can someone provide an update as to why it's been parked?

**Comment by johnsimons** [comment]
Upgrade has been cancelled.
